# Generated by Django 6.0.3 on 2026-04-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_projectfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
