# Generated by Django 6.0.3 on 2026-04-06 21:01

import apps.files.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_projectfile_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes, stored at upload time'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='public_id',
            field=models.CharField(blank=True, default='', help_text='Cloudinary public_id for authenticated uploads', max_length=500),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='resource_type',
            field=models.CharField(default='auto', help_text='Cloudinary resource_type (image, video, raw, auto)', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.files.models.get_project_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg', 'zip']), apps.files.models.validate_file_size, apps.files.models.validate_file_type]),
        ),
    ]
