# Generated by Django 5.1.15 on 2026-04-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_secure_file_fields'),
        ('users', '0002_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='original_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.workspace'),
        ),
    ]
