# Generated by Django 6.0.3 on 2026-04-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('agency', 'Agency')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
