# Generated by Django 6.0.3 on 2026-04-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_plan_user_plan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
