# Generated by Django 5.2.4 on 2026-03-13 19:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('freelancer', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ClientPortal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
