# Generated by Django 5.2.4 on 2026-03-18 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='portal_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
