# Generated by Django 5.2.4 on 2026-03-18 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_portal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='portal_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='ClientPortal',
        ),
    ]
