# Generated by Django 6.0.3 on 2026-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_unique_token_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='portal_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
