# Generated by Django 6.0.3 on 2026-04-26 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('niche', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('audience_size', models.CharField(blank=True, max_length=50)),
                ('warmth', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='cold', max_length=10)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('sent', 'Sent'), ('replied', 'Replied'), ('demo', 'Demo'), ('converted', 'Converted'), ('lost', 'Lost')], default='lead', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sent', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('demo', models.BooleanField(default=False)),
                ('converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
